### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by TheDataLion** [andresbytes/NpcDialog#8]
It looks like Minecraft changed something.
When the dialog should open it opens a dialog edit menu instead.
Thats something it shouldn't do.

**Comment by thebigsmileXD** [comment]
![image](https://user-images.githubusercontent.com/8733998/99325566-f238e900-2876-11eb-907c-01694d7cb457.png)
Just noticed it as well. Clicking "edit dialog" opens the dialog like before

**Comment by thebigsmileXD** [comment]
![image](https://user-images.githubusercontent.com/8733998/102006548-4e7e1400-3d22-11eb-87ca-b61f2b017508.png)
I just saw this on https://minecraft.gamepedia.com/NPC#Interface, apparently it is permission based and can not be stopped

**Comment by DataLiontje** [comment]
> ![image](https://user-images.githubusercontent.com/8733998/102006548-4e7e1400-3d22-11eb-87ca-b61f2b017508.png)
> 
> I just saw this on https://minecraft.gamepedia.com/NPC#Interface, apparently it is permission based and can not be stopped

So that means we have to find a way to get rid of those permissions🤔

**Comment by thebigsmileXD** [comment]
> So that means we have to find a way to get rid of those permissions🤔

I actually raised a complain at Mojang, hence the new simulation type packet. I is still in beta, and the dialogues will get nested trees. So we just need to wait a bit

**Comment by ananinys** [comment]
Is it possible to fix this error yourself? :(

**Comment by thebigsmileXD** [comment]
> Is it possible to fix this error yourself? :(

There is no fix possible currently. As a workaround you could remove your operator permission

**Comment by thebigsmileXD** [comment]
On a side note, dialogues can be opened from the server side since 1.17.10

**Comment by ananinys** [comment]
> On a side note, dialogues can be opened from the server side since 1.17.10

this causes an error. You can check it out for yourself

**Comment by thebigsmileXD** [comment]
https://bugs.mojang.com/browse/MCPE-135686

**Comment by ananinys** [comment]
> https://bugs.mojang.com/browse/MCPE-135686

how much longer do you need to wait for a fix from mojang? :(

**Comment by thebigsmileXD** [comment]
5 years and it gets longer every time you ask.
